### ISSUE TITLE
Getting error while executing command

### ISSUE THREAD

**Issue by dedhdude** [mongodb-js/boxednode#7]
boxednode -s index.js -t abc
internal/util.js:206
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at Object.promisify (internal/util.js:206:11)
    at Object.<anonymous> (/root/.nvm/versions/node/v8.4.0/lib/node_modules/boxednode/s.js:14:27)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v8.4.0/lib/node_modules/boxednode/-addons.js:11:19)

**Comment by addaleax** [comment]
Hi @dedhdude!

As stated in the README and the package.json, the minimum supported version to use boxednode is Node v12.x. You’re using Node v8.x, which is not supported or tested (and not supported by Node.js itself anymore either). If you switch to Node v12.x or higher, this should work fine :slightly_smiling_face:

**Comment by dedhdude** [comment]
Thanks
